#[env]
#TERM = "xterm-256color"

[window]
opacity = 0.75

[font]
size = 14

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
